version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-29
    environment:
      - GRADLE_OPTS: -PdisablePreDex -Pandroid.useAndroidX=true -Pandroid.enableJetifier=true clean patient:appDistributionUploadInternalRelease --no-daemon --max-workers 3
    resource_class: large
    steps:
      - checkout:
          path: ~/project/complete
      - run:
          name: Set environment variable to export
          command: |
            echo 'export FIREBASE_TOKEN="${FIREBASE_TOKEN}"' >> $BASH_ENV
      - run:
          name: Try Gradlew
          command: ./gradlew dependencies

workflows:
  start_build:
    jobs:
      - build