version: 2.1

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      - GRADLE_OPTS: -Xmx3g -Dkotlin.compiler.execution.strategy=in-process
    resource_class: large
    steps:
      - checkout
      - run:
          name: Set environment variable to export
          command: |
            echo 'export FIREBASE_TOKEN="${FIREBASE_TOKEN}"' >> $BASH_ENV
      - run:
          name: Try Gradlew
          command: ./gradlew -PdisablePreDex -Pandroid.useAndroidX=true -Pandroid.enableJetifier=true clean patient:appDistributionUploadInternalRelease --no-daemon --max-workers 3

workflows:
  start_build:
    jobs:
      - build